# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-18.04"
  config.vm.hostname = "dev1.example.com"
  config.vm.define "dev1.example.com"
  config.vm.provider :virtualbox do |vb|
    vb.name = "dev1.example.com"
  end
  config.vm.network "forwarded_port", guest: 80, host: 8000

  config.vm.provision "shell", inline: <<-SHELL
    sudo apt install -y ansible
    cd /vagrant
    ansible-playbook playbook.yml
  SHELL

#  config.vm.provision "ansible_local" do |ansible|
#    ansible.playbook = "playbook.yml"
#  end

#  config.vm.provision "ansible" do |ansible|
#    ansible.playbook = 'playbook.yml'
#  end
end
